
class Scanner:
    def __cinit__(self) -> None: ...
    def __init__(self, *args, **kwargs) -> None: ...
    def __dealloc__(self) -> None: ...
    def __iter__(self): ...
    def __next__(self): ...
